### PR TITLE
Update to websocketpp 0.8.1

### LINKED ISSUE #15: Failure to build with openssl-1.1
When trying to install the package on a machine with openssl-1.1, the following error is thrown:
`‘SSL_R_SHORT_READ’ was not declared in this scope`

This was solved by the release of version 0.8 of Websocket++ (see https://github.com/zaphoyd/websocketpp/issues/599 and https://github.com/zaphoyd/websocketpp/releases/tag/0.8.0), so I suspect that updating this package  to utilize the newer version of Websocket++ would solve the installation issues.

### PR DESCRIPTION
**Pull request by jcheng5**
This fixes #15, but also requires https://github.com/eddelbuettel/asioheaders/pull/2 to fully compile with OpenSSL 1.1.0.

### CODE REVIEW

**Comment by jcheng5** [comment]
Ideally, we'll wait to release to CRAN until asioheaders 1.12.1 goes up, and we'll take a version dependency on it.
