### ISSUE TITLE
Failure to build with openssl-1.1

### ISSUE THREAD

**Issue by ef2240** [rstudio/websocket#15]
When trying to install the package on a machine with openssl-1.1, the following error is thrown:
`‘SSL_R_SHORT_READ’ was not declared in this scope`

This was solved by the release of version 0.8 of Websocket++ (see https://github.com/zaphoyd/websocketpp/issues/599 and https://github.com/zaphoyd/websocketpp/releases/tag/0.8.0), so I suspect that updating this package  to utilize the newer version of Websocket++ would solve the installation issues.

**Comment by jcheng5** [comment]
Thanks for the report. What platform are you on?

**Comment by ef2240** [comment]
Thanks for following up. I'm on x86_64-pc-linux-gnu (64-bit) running under Debian GNU/Linux 9 (stretch). More specifically, I'm using the rocker/tidyverse:3.5.0 docker image (https://hub.docker.com/r/rocker/tidyverse/)

**Comment by jcheng5** [comment]
(Note mostly for myself) Upgrading to a newer version of websocketpp is necessary but turns out not to be sufficient--the AsioHeaders package also needs to be upgraded.

**Comment by jcheng5** [comment]
For now:

```r
devtools::install_github(c("eddelbuettel/asioheaders#2", "rstudio/websocket#23"))
```
